apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# In prod: more replicas, stricter resources
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: sporttrack-api

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: sporttrack-frontend

images:
  - name: YOUR_DOCKERHUB_USER/sporttrack-api
    newTag: "1.0.0"      # pinned tag in prod, not :latest
  - name: YOUR_DOCKERHUB_USER/sporttrack-frontend
    newTag: "1.0.0"
